version: '3.3'

services:

  webserver:
    image: sitepilot/webserver:test
    container_name: webserver-test
    ports:
      - "8080:80"
      - "8443:443"
      - "7081:7080"
    restart: always
    environment:
      WEBSERVER_USER_ID: 1000
      WEBSERVER_USER_GID: 1000
      WP_INSTALL: "yes"