version: '3.3'

services:

  webserver:
    image: sitepilot/webserver:test
    container_name: webserver
    ports:
      - "81:80"
      - "444:443"
      - "7081:7080"
    restart: always
    environment:
      WEBSERVER_USER_ID: 1000
      WEBSERVER_USER_GID: 1000