name: deploy

on: push

jobs:

  deploy:
 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v1
    - name: Build and deploy the Docker image
      run: |
        echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
        docker build . --file Dockerfile --tag sitepilot/webserver:${GITHUB_REF##*/}
        docker push sitepilot/webserver:${GITHUB_REF##*/}
